/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxStm.h"
#include "Ifx_Cfg_Ssw.h"
#include "Flash4_Driver.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED1                        &MODULE_P00,5   /* LED1 Port, Pin definition (status LED) */
#define LED2                        &MODULE_P00,6   /* LED2 Port, Pin definition (debug LED)  */
#define TEST_ADDRESS                0x00001234      /* Test address in flash     */
#define TEST_DATA_SIZE              16              /* Test data size in bytes   */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

/* Test data buffers */
uint8 g_writeBuffer[TEST_DATA_SIZE] = "MikroElektronika";  /* Data to write */
uint8 g_readBuffer[TEST_DATA_SIZE];                        /* Buffer for read data */
uint8 g_deviceId[2];                                       /* Device ID buffer */

/* Test result and status flags */
volatile boolean g_testPassed = FALSE;
volatile uint8 g_errorStep = 0;  /* 0=no error, 1=ID fail, 2=erase fail, 3=write fail, 4=read fail, 5=verify fail */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initLED(void);
void testFlash4(void);
void waitMs(uint32 ms);

/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/

/* Initialize LED */
void initLED(void)
{
    /* Set LED1 pin as output push-pull mode */
    IfxPort_setPinModeOutput(LED1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    
    /* Set LED2 pin as output push-pull mode */
    IfxPort_setPinModeOutput(LED2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    
    /* Turn off both LEDs (LEDs are low-level active) */
    IfxPort_setPinHigh(LED1);
    IfxPort_setPinHigh(LED2);
}

/* Simple delay function */
void waitMs(uint32 ms)
{
    uint32 startTime = IfxStm_get(&MODULE_STM0);
    uint32 ticksPerMs = (uint32)(IfxStm_getFrequency(&MODULE_STM0) / 1000u);
    uint32 delay = ms * ticksPerMs;
    
    while((IfxStm_get(&MODULE_STM0) - startTime) < delay);
}

/* Test Flash4 read/write functionality */
void testFlash4(void)
{
    uint8 i;
    boolean dataMatch = TRUE;
    
    /* Clear read buffer */
    for(i = 0; i < TEST_DATA_SIZE; i++)
    {
        g_readBuffer[i] = 0;
    }
    
    /* Step 1: Read Device ID */
    IfxPort_setPinLow(LED1);  /* LED1 ON - Start testing */
    Flash4_ReadManufacturerId(g_deviceId);
    
    /* Verify manufacturer ID */
    if(g_deviceId[0] != FLASH4_MANUFACTURER_ID)
    {
        /* ID mismatch - flash might not be connected properly */
        g_errorStep = 1;
        return;
    }
    
    waitMs(500);
    IfxPort_setPinHigh(LED1);  /* LED1 OFF */
    
    /* Step 2: Enable write */
    IfxPort_setPinLow(LED2);   /* LED2 ON - Erasing */
    Flash4_WriteCommand(FLASH4_CMD_WRITE_ENABLE_WREN);
    waitMs(10);
    
    /* Step 3: Erase sector at test address */
    Flash4_SectorErase4(TEST_ADDRESS);
    
    /* Wait for erase to complete (sector erase can take several seconds) */
    if(Flash4_WaitReady(5000) != FLASH4_OK)
    {
        /* Timeout during erase */
        g_errorStep = 2;
        return;
    }
    
    waitMs(100);
    IfxPort_setPinHigh(LED2);  /* LED2 OFF */
    
    /* Step 4: Enable write again for programming */
    IfxPort_setPinLow(LED1);   /* LED1 ON - Programming */
    Flash4_WriteCommand(FLASH4_CMD_WRITE_ENABLE_WREN);
    waitMs(10);
    
    /* Step 5: Write data to flash */
    Flash4_PageProgram4(g_writeBuffer, TEST_ADDRESS, TEST_DATA_SIZE);
    
    /* Wait for program to complete */
    if(Flash4_WaitReady(1000) != FLASH4_OK)
    {
        /* Timeout during programming */
        g_errorStep = 3;
        return;
    }
    
    waitMs(100);
    IfxPort_setPinHigh(LED1);  /* LED1 OFF */
    
    /* Step 6: Read back data from flash */
    IfxPort_setPinLow(LED2);   /* LED2 ON - Reading */
    Flash4_ReadFlash4(g_readBuffer, TEST_ADDRESS, TEST_DATA_SIZE);
    
    /* Wait for read to complete */
    if(Flash4_WaitReady(1000) != FLASH4_OK)
    {
        /* Timeout during read */
        g_errorStep = 4;
        return;
    }
    
    waitMs(100);
    IfxPort_setPinHigh(LED2);  /* LED2 OFF */
    
    /* Step 7: Verify data */
    for(i = 0; i < TEST_DATA_SIZE; i++)
    {
        if(g_readBuffer[i] != g_writeBuffer[i])
        {
            dataMatch = FALSE;
            break;
        }
    }
    
    if(dataMatch)
    {
        g_testPassed = TRUE;
    }
    else
    {
        g_errorStep = 5;
    }
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    
    /* Initialize LED */
    initLED();
    
    /* Initialize Flash4 QSPI interface */
    Flash4_Init();
    
    /* Wait for flash to be ready */
    waitMs(100);
    
    /* Perform Flash4 test */
    testFlash4();
    
    /* Display result with LED patterns */
    if(g_testPassed)
    {
        /* Success: Both LEDs ON */
        IfxPort_setPinLow(LED1);
        IfxPort_setPinLow(LED2);
    }
    else
    {
        /* Error: Blink pattern based on error step */
        while(1)
        {
            uint8 i;
            /* Blink LED1 to show error step number */
            for(i = 0; i < g_errorStep; i++)
            {
                IfxPort_setPinLow(LED1);
                waitMs(200);
                IfxPort_setPinHigh(LED1);
                waitMs(200);
            }
            
            /* Long pause */
            waitMs(1000);
            
            /* Blink LED2 continuously to show error state */
            IfxPort_setPinLow(LED2);
            waitMs(100);
            IfxPort_setPinHigh(LED2);
            waitMs(100);
        }
    }
    
    while(1)
    {
        /* Main loop - test is complete */
        /* Success: Both LEDs ON */
        /* Error: LED1 blinks N times (N = error step), LED2 blinks continuously */
    }
}
